### PR TITLE
[BD-26][EDUCATOR-5774, EDUCATOR-5758] Add API for fetching proctoring settings

### PR DESCRIPTION
**Pull request by UvgenGen**
- Implement API and reducers to use proctoring settings endpoint.
- add Entrance, Verification, Submit, Submitted, Verified, Rejected instructions

JIRA: [EDUCATOR-5774](https://openedx.atlassian.net/browse/EDUCATOR-5774), [EDUCATOR-5758](https://openedx.atlassian.net/browse/EDUCATOR-5758)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @UvgenGen! I've created [BLENDED-850](https://openedx.atlassian.net/browse/BLENDED-850) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by idegtiarov** [comment]
@Zacharis278  Please review )))

**Comment by Zacharis278** [comment]
@UvgenGen can you rebase/merge this with `main`? Looks like these changes were included when I merged #7

**Comment by UvgenGen** [comment]
I checked.  Yes, these changes were included when merging #7.
We can close this PR too.

**Pull request closed without merging**
