### PR TITLE
build: integrate commitlint

### PR DESCRIPTION
**Pull request by schenedx**
Integrate commitlint into the repository pre-commit check so commit messages can trigger semantic-release properly.

See example failed commit messaging below:
Screen Shot 2021-09-23 at 3 32 17 PM

### CODE REVIEW

**Review by ashultz0 — APPROVED** [review]

**Comment by Zacharis278** [comment]
a thought, would the be better to attach to the github CI instead of running on commit which can be ignored?

**Comment by schenedx** [comment]
@Zacharis278 Running commitlint on github CI sounds like a good idea. Why not have both?

**Comment by Zacharis278** [comment]
both sounds fine. What I am realizing is that this isn't foolproof since ultimately the commit that goes into master comes from the github webui. 🙃

**Comment by schenedx** [comment]
@Zacharis278 I guess. But the enforcement are here to make it difficult to make mistake. That should be enough.

**Review by Zacharis278 — APPROVED** [review]

**Pull request merged**
