### PR TITLE
[BD-26][EDUCATOR-5813] Add pages for pending/failed prerequisites

### PR DESCRIPTION
**Pull request by ViktorRusakov**
This PR adds pages for failed/pending prerequisites if user has any

NOTE: should be merged after #10 

JIRA: [EDUCATOR-5813](https://openedx.atlassian.net/browse/EDUCATOR-5813)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ViktorRusakov! I've created [BLENDED-856](https://openedx.atlassian.net/browse/BLENDED-856) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by Zacharis278** [comment]
can you do a rebase to catch us up with previous changes? hard to view the diff otherwise

**Comment by ViktorRusakov** [comment]
@Zacharis278 this should be merged after #10

**Comment by Zacharis278** [comment]
@ViktorRusakov new views and tests look good, will give a thumb once we've resolved the conflicts

**Comment by ViktorRusakov** [comment]
@Zacharis278 updated the branch, ready to be merged now. Also please check out PRs in edx-proctoring, mainly [this](https://github.com/edx/edx-proctoring/pull/864) and [this](https://github.com/edx/edx-proctoring/pull/865), since they both correspond to the two PRs being merged here today

**Comment by ViktorRusakov** [comment]
I have also noted the issues from previous PR, I will bring them up tomorrow in our internal sync so we can keep them in mind and get it fixed

**Review by Zacharis278 — APPROVED** [review]

**Pull request merged**
