### PR TITLE
[BD-26] Add handling of second review required status for proctored exams

### PR DESCRIPTION
**Pull request by ViktorRusakov**
Fix missing second_review_required status for proctored exams, which resulted in showing exam content to the student

JIRA: [EDUCATOR-5909](https://openedx.atlassian.net/browse/EDUCATOR-5909)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ViktorRusakov! I've created [BLENDED-928](https://openedx.atlassian.net/browse/BLENDED-928) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by ViktorRusakov** [comment]
@Zacharis278 I noticed that in LMS this attempt status (and some others) are handled [differently](https://github.com/edx/edx-proctoring/blob/68827c066e3afcbc3fc57ae3c991077f876b53b2/edx_proctoring/api.py#L2745) for proctored exams

do we also need to add that check which uses `_was_review_status_acknowledged` function to our API? I don't think we do that check right now

**Review by idegtiarov — APPROVED** [review]
LGTM!

**Review by UvgenGen — APPROVED** [review]

**Comment by Zacharis278** [comment]
this bug has me thinking that we should be more strict about rendering the `children` in this function. If someone added a new backend attempt state it would automatically show the exam content. Can we make that case more specific to only render content for a started attempt or a timed exam that is viewable after submission?

**Comment by ViktorRusakov** [comment]
Yeah, we can do that, but what should the default behaviour be then? What do we show if unknown status came from the backend?

**Comment by Zacharis278** [comment]
@ViktorRusakov I think we can just add a simple error template. We don't really expect to ever hit this case unless something has gone wrong

**Comment by ViktorRusakov** [comment]
@Zacharis278 I've updated the PR to handle unknown statuses, please take a look

**Review by idegtiarov — APPROVED** [review]
lgtm

**Review by Zacharis278 — APPROVED** [review]
thanks! This looks good, can you queue up the version bump for the learning MFE as well?

**Comment by ViktorRusakov** [comment]
sure, I've opened new PR [here](https://github.com/edx/frontend-app-learning/pull/564)

waiting for this to be merged and I'll update it then

**Pull request merged**
