### PR TITLE
[BD-26] Fix a bug with JS worker

### PR DESCRIPTION
**Pull request by ViktorRusakov**
This PR fixes a bug where JS worker would not send onStartAttempt message to proctoring backend provider when proctoring exam starts.

NOTE: should be merged after #11 and #12 are both merged

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ViktorRusakov! I've created [BLENDED-861](https://openedx.atlassian.net/browse/BLENDED-861) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by Zacharis278** [comment]
can you rebase this one so commits from #11 are included?

**Comment by ViktorRusakov** [comment]
> can you rebase this one so commits from #11 are included?

can you please merge #18 first? I think every other currently open PR contains commits from that one, it seems we forgot to open that PR in time and now order is messed up a little

**Comment by ViktorRusakov** [comment]
closing this one since it's part of #15

**Pull request closed without merging**
