### PR TITLE
[BD-26][EDUCATOR-5791, EDUCATOR-5767] Add handling of exam API errors and support for js workers from provider

### PR DESCRIPTION
**Pull request by ViktorRusakov**
This PR allows user-friendly handling of exam API errors (previously the errors would just be printed in the console) and also adds support for js workers from proctoring providers

JIRA: [EDUCATOR-5791](https://openedx.atlassian.net/browse/EDUCATOR-5791) [EDUCATOR-5767](https://openedx.atlassian.net/browse/EDUCATOR-5767)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ViktorRusakov! I've created [OSPR-5791](https://openedx.atlassian.net/browse/OSPR-5791) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by idegtiarov** [comment]
@ViktorRusakov  Please add `[BD-26]`

**Comment by idegtiarov** [comment]
@Zacharis278  Please review )))

**Review by Zacharis278 — APPROVED** [review]
Looks Good 👍

**Pull request merged**
