### PR TITLE
fix: update frontend-platform to avoid peer dependency error

### PR DESCRIPTION
**Pull request by dcoa**
**Description**

Now `npm ci` check peer dependency. 
Update frontend-platform to avoid peer dependency errors.
This allows updating this package in the app. 

This is the error when running `npm ci` master branch using node v16.15.1 (npm v8.11.0)
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @edx/frontend-platform@1.8.4
npm ERR! Found: @edx/paragon@19.14.1
npm ERR! node_modules/@edx/paragon
npm ERR!   dev @edx/paragon@"19.14.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @edx/paragon@">=10.0.0 <14.0.0" from @edx/frontend-platform@1.8.4
npm ERR! node_modules/@edx/frontend-platform
npm ERR!   dev @edx/frontend-platform@"1.8.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @edx/paragon@13.17.5
npm ERR! node_modules/@edx/paragon
npm ERR!   peer @edx/paragon@">=10.0.0 <14.0.0" from @edx/frontend-platform@1.8.4
npm ERR!   node_modules/@edx/frontend-platform
npm ERR!     dev @edx/frontend-platform@"1.8.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/dcoa/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dcoa/.npm/_logs/2022-07-13T20_08_31_307Z-debug-0.log
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dcoa!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by kdmccormick** [comment]
@schenedx could someone from Cosmonauts review this PR soon?

**Comment by schenedx** [comment]
@kdmccormick Thank you for the pin.
Created an internal Jira ticket to track and prioritize this review request.

**Comment by kdmccormick** [comment]
Thanks Simon. When prioritizing this, please note that's its a 3 line change and has been open since July.

**Comment by kdmccormick** [comment]
Some context on why this PR is important: it blocks [this learning MFE PR](https://github.com/openedx/frontend-app-learning/pull/955), which adds [runtime configuration]( https://github.com/openedx/frontend-wg/issues/103) support to the MFE.

In Olive (which has been cut, and is being prepared for a Dec 9 release), we need all included MFEs to support runtime configuration so that the Tutor MFE image can build performantly. Going forward, this will allow us to add many/all MFEs to the community release without slowing down the installation process. This will allow us to finally drop support for the many legacy frontend pages that are still used in the community release, freeing up time for developers and reducing the complexity of the platform.

**Review by Zacharis278 — APPROVED** [review]
this looks Trying to figure out why the github checks aren't running on this

**Comment by kdmccormick** [comment]
Maybe it's an `edx` org setting that prevents actions from running on PRs from forks?

If that's the case you could always close this and reopen it from a branch in the `edx` upstream repo.

**Comment by Zacharis278** [comment]
@kdmccormick I usually just have to approve the workflow run for a fork if the author isn't an approved committer but in this case the entire checks page is just... blank.  I'll just pull this into an edx branch if I can't figure out what's going on here.

**Comment by Zacharis278** [comment]
thanks! This is now covered by #73.  Closing

**Comment by openedx-webhooks** [comment]
@dcoa Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-lib-special-exams&entry.867055334=https://github.com/edx/frontend-lib-special-exams/pull/70&entry.1484655318=https://github.com/dcoa&entry.752974735=2022-07-13+21:35&entry.1917517419=2022-10-19+18:18&entry.2133058324=No) so we can improve your experience in the future.

**Comment by kdmccormick** [comment]
Thanks @Zacharis278 !

**Pull request closed without merging**
